name: Run daily jests tests (TypeScript) on GitHub Actions

on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 0 * * *"

branch: main

jobs:
  run-tests-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: tests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Create folder
        run: npm start

      - name: Run jest tests
        run: npm run test
